### ISSUE TITLE
Images not added to the blob when using the IMG tag

### ISSUE THREAD

**Issue by marcelinollano** [bebanjo/releases-builder#1]
Sometimes GitHub adds the `<img>` tag when uploading files to the body of the issue. We are just checking for markdowns `![]()` at the moment. As a result the images are linked but not added to the blob of the commit.

**Comment by marcelinollano** [comment]
This is fixed now, we can use both the `<IMG>` and `![]()` format when adding images, plus I added better logging in case I have to debug this again. If we have further problems I will have to test this properly.

**Comment by maxcosworth** [comment]
@marcelinollano, I can't close this one, could you please add us to the repo or close the issue yourself? Thanks!
